### ISSUE TITLE
Need to add keys to lists

### ISSUE THREAD

**Issue by rafauoo** [rafauoo/rick-and-morty-page#6]
react-jsx-dev-runtime.development.js:87 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `EpisodesList`. See https://reactjs.org/link/warning-keys for more information.
    at li
    at EpisodesList (http://localhost:3000/static/js/bundle.js:262:63)
    at div
    at body
    at Body
    at div
    at App
    at ApolloProvider (http://localhost:3000/static/js/bundle.js:49508:19)

**Comment by rafauoo** [comment]
Added keys to lists
